name: skills_path_app
description: Una aplicación de gamificación para el desarrollo de habilidades blandas.

# La versión siguiente debe incrementarse cada vez que publiques en Play Store.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Los siguientes añaden íconos de Material Design.
  cupertino_icons: ^1.0.2

  # Para manejo de estado
  provider: ^6.0.5

  # Para almacenamiento local
  shared_preferences: ^2.2.2

  # Para notificaciones push
  firebase_messaging: ^14.7.10

  # Para base de datos local
  sqflite: ^2.3.0

  # Para manejo de rutas
  go_router: ^12.1.1

  # Para manejo de peticiones
  http: ^1.2.1

  html: ^0.15.4

  flutter_html: ^3.0.0-beta.2

  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Las reglas de "lints" para este paquete están especificadas en
  # package:flutter_lints/flutter.yaml. Estas incluyen reglas adicionales
  # de código que están hechas específicamente para Flutter.
  flutter_lints: ^2.0.0

# Para información sobre la sección genérica de Yaml, ver la siguiente página:
# https://dart.dev/tools/pub/pubspec

# La siguiente sección es específica de Flutter.
flutter:

  # Esta línea asegura que el Material Icons font se
  # incluya en la aplicación, para que puedas usar los íconos
  # de la clase Icons.
  uses-material-design: true

  # Para añadir assets a tu aplicación, añade una sección assets, como esta:
  assets:
    - assets/images/
    - assets/icons/

  # Un ejemplo de font family:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700